name: Update IPTV Playlist Token

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Для корректного push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python auto_token_gen.py

      - name: Check and commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add NightTV.m3u
          git status  # Отладка: показать статус файлов

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Автообновление IPTV токена [skip ci]"
            git push origin HEAD:main
          fi
